### ISSUE TITLE
Default pipeline - automatic `vnni` packing

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#257] opened 2023-01-06 12:36 UTC
`-pack-vnni` pass is currently required to go from linalg to VNNI.
`vnni` packing requires users to specify the blocking factor. By default, only full tiles are supported i.e., `dimension % block-factor == 0`. Optionally, a `padding_value` can also be supplied to ensure clean tiling and enable the lowering to VNNI.

The TPP's default pipeline should be able to handle any types on inputs and tensor shapes. Thus, it is required to analyze ops suitable for VNNI packing and select appropriate setting values for the packing pass. This should be done automatically without need for any user input.

The main goals:
- extend the `DefaultTppPasses` with an analysis step that computes the `block-factor` and the `padding_value` for each relevant op (currently, `linalg.matmul` and `linalg.brgemm`)
- create VNNI packing pass on demand with the dynamically computed options
- the computed options do not have to be optimal - generic value that just works for all inputs should be enough for now

**Comment by adam-smnk** [comment] 2023-01-06 13:03
One thing to consider is whether we even need to go from linalg to VNNI. The direct lowering `-convert-linalg-to-tpp` currently covers all our use-cases at the post-bufferization stage.
So, the automated packing (or general lowering) from linalg to VNNI could be ignored until a new use-cases come up e.g., need to stay at the tensor level longer.

**Comment by rengolin** [comment] 2023-03-17 15:27
Duplicate of #361

**Closed by rengolin** 2023-03-17 15:27 UTC
