### ISSUE TITLE
SPR scalability issue

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#895] opened 2024-03-01 12:08 UTC
Libxsmm-dnn gets 10x scalability on SPR where tpp-mlir gets 14x but only because it reaches the same performance plateau (~19TF). This is probably a memory issue.

![omp-spr-16](https://github.com/plaidml/tpp-mlir/assets/1040968/2a0643ee-c707-4dec-9965-c2a1fe786108)

**Comment by alheinecke** [comment] 2024-03-01 16:56
I suggest we merge this as duplicate of #893.

The parallel performance is good, even for 2 threads things are identical. The different scalability is a red herring here... It's all about single thread variation.

**Closed** 2024-03-01 17:04 UTC
